- vite.config.ts
> 🔨chore: Change pwa config settings

- eslint.config.js
- src/main.tsx
> chore: Add missing parts of plugin

- .gitignore
- src/supabaseClient.ts
- vite.config.ts
- #17 
- supabase.ts 생성
- config 수정
> supabase 초기 세팅

- package-lock.json
- src/components/ui/button.tsx
- src/lib/utils.ts
- src/pages/AdditionalInfoPage/AdditionalInfoPage.tsx
- src/pages/EventPage/EventPage.tsx
- src/pages/InfoPage/InfoPage.tsx
- src/pages/LoginPage/LoginPage.tsx
- src/pages/MainPage/MainPage.tsx
- src/pages/MembershipPage/MembershipPage.tsx
- src/pages/NetworkingClubPage/NetworkingClub.tsx
- src/pages/NetworkingListPage/NetworkingListPage.tsx
- src/pages/NotFoundPage/NotFoundPage.tsx
- src/pages/NotificationPage/NotificationPage.tsx
- src/pages/PremiumEventPage/PremiumEventPage.tsx
- src/pages/SelectCardDesignPage/SelectCardDesignPage.tsx
- src/pages/SignupPage/SignupPage.tsx
- src/pages/UserCardPage/UserCardPage.tsx
- src/pages/UserPage/UserPage.tsx
- src/pages/UserSettingPage/UserSettingPage.tsx
- src/routes/RoutePath.ts
- src/routes/index.tsx
- tsconfig.app.json
- #15 
- 페이지 생성 & 루트 설정
수정이 필요합니다.
> 페이지 생성 & 루트 설정

- package-lock.json
- package.json
- src/App.tsx
- src/pages/MainPage/MainPage.tsx
- src/routes/index.tsx
- src/store/slices/counterSlice.ts
- src/store/store.ts
- vite.config.ts
> redux 세팅 & router 적용

- src/components/commons/Card/Card.tsx
- #33 
- 카드 컴포넌트 추가
- 
- 카드 기능
- 마우스 호버 -> 이동 시 카드 컴포넌트 움직임 & 유광처리 (추후 빼도 됨)
> :sparkles:feat: add card component

- package-lock.json
- package.json
- src/App.tsx
- src/components/UserInterestsPage/InterestSelector.tsx
- src/components/commons/Card/Card.tsx
- src/pages/AdditionalInfoPage/AdditionalInfoPage.tsx
- src/pages/CardPreviewPage/CardPreviewPage.tsx
- src/pages/RealCardScanPage/RealCardScanPage.tsx
- src/pages/SelectCardDesignPage/SelectCardDesignPage.tsx
- src/pages/UserInterestsPage/UserInterestsPage.tsx
- src/routes/RoutePath.ts
- src/routes/index.tsx
- src/shared/types/dom-to-image-more.d.ts
- #26 
- 명함 생성 기능 구현
- 카드 디자인 페이지
- 선택한 카드 디자인에 따라 미리보기 표시
- 추가 정보 입력 페이지
- 실제 명함 스캔 페이지
- 카메라를 이용한 실제 명함 스캔
- 데이터 추출  
- 관심사 선택 페이지
- 명함 생성 완료 & 미리보기 페이지
- dom-to-image-more (추후 사용 예정)
- 컴포넌트를 이미지로 변환하는 라이브러리 
- react-webcam
- 실제 명함 스캔을 위한 카메라 기능 라이브러리  
> 명함 생성 기능 구현

- src/components/NetworkingListPage/Card.tsx
- src/components/commons/QR/QRDrawer.tsx
- src/components/commons/QRcodeDisplay.tsx
- src/pages/AdditionalInfoPage/AdditionalInfoPage.tsx
- src/pages/MainPage/MainPage.tsx
- src/pages/QrScannerPage/QrScannerPage.tsx
- src/pages/UserCardPage/UserCardPage.tsx
- src/routes/index.tsx
- #38 
- QR Drawer 생성
- QR 표시, QR 스캔 버튼 유저 명함 페이지로 이동
- QR Drawer 생성
- 1분
> QR Drawer 컴포넌트 추가

- src/pages/UserCardPage/UserCardPage.tsx
- #44 
- qr-scan 페이지로 이동하도록 버튼 onClick 수정
> qr-scan 페이지로 이동하도록 버튼 onClick 수정

- package-lock.json
- package.json
- src/components/UserInterestsPage/InterestSelector.tsx
- src/components/commons/Card/Card.tsx
- src/pages/CardPreviewPage/CardPreviewPage.tsx
- src/pages/RealCardScanPage/RealCardScanPage.tsx
- #46
- 실제 명함 스캔 결과 drawer UI 변경
- 관심사 선택 페이지 UI 변경
- 카드 UI 변경
- 실제 명함 스캔 결과 많을 경우 버튼이 보이도록 레이아웃 조정
- 관심사 & 아이콘 추가
- 카드 폰트 사이즈 변경 / 아이콘 추가 / 각도 조절
- 리뷰 예상 시간: 1분
> 명함 생성 디자인 개선

- src/pages/BusinessCardBookPage/BusinessCardBookPage.tsx
- src/routes/RoutePath.ts
- src/routes/index.tsx
- #51 
- 명함첩 페이지 추가
- 페이지 추가
- 루트 설정
- 리뷰 예상 시간: 1분
> 명함첩 페이지 추가

- src/components/SignupPage/FirstStep.tsx
- src/components/SignupPage/SecondStep.tsx
- src/components/SignupPage/Signup.tsx
- src/components/SignupPage/signupSchema.ts
- src/constants/expertiseConstants.ts
- src/features/SignupPage/api/infoDuplicateCheckApi.ts
- src/utils/formatPhoneNumber.ts
- #75 
- 디자인
- 유효성 검사 강화
- 핸드폰 번호 추가
- 디자인 맞춰 레이아웃 개선
- 헤더 등 디테일 개선 필요
- 유효성 검사 강화
- 검사 통과 성공 메시지 표시
- 스키마 강화
- 핸드폰 번호 추가
- 핸드폰 번호 중복 검사 API 구현
- 핸드폰 번호 유효성 검사 스키마 추가
- 핸드폰 번호 형식 변환 유틸 함수 추가 
- 리뷰 예상 시간: 10분
> 회원가입 페이지 개선

- src/components/commons/QR/QRDisplayTabContent.tsx
- src/components/commons/QR/QRScanDisplayModal.tsx
- src/components/commons/QR/QRScannerTabContent.tsx
- src/hooks/useWindowHeight.ts
- src/hooks/useWindowWidth.ts
- src/pages/MainPage/MainPage.tsx
- #85 
- 디바이스에 따라 캐러셀 다르게 표시
- 디바이스 너비 & 높이 측정 훅 분리
- 디바이스에 따라 캐러셀 padding 다르게 설정
- 리뷰 예상 시간: 5분
> QR 스캔 & 표시 모달 개선

- src/features/User/api/viewCountApi.ts
- src/pages/UserCardPage/UserCardPage.tsx
- src/routes/RoutePath.ts
- src/store/store.ts
- #93 
- 조회수 증가 API 구현
- 명함 상세 페이지에 적용
- Supabase rpc로 API 구현
- Url 의 nickname 과 userSlice의 nickname이 일치하지 않으면 API 요청 X
- 리뷰 예상 시간: 5분
> 조회수 증가 API 구현

- src/components/commons/Card/TypeCardCarousel.tsx
사용하지 않는 props 삭제
- #112
props 삭제
- 리뷰 예상 시간: 3초
> 사용하지 않는 props 삭제

- src/components/commons/Card/HorizontalCard.tsx
- src/components/commons/Card/TypeCardCarousel.tsx
- src/pages/SelectCardDesignPage/SelectCardDesignPage.tsx
- #115 
- 카드 디자인 선택 페이지 그라디언트 적용
- 가로 카드 레이아웃 적용
- 선택된 타입에 따라 다른 그라디언트 적용
- 전환시 트랜지션 적용
- 가로 카드 레이아웃 변경사항 적용
- 리뷰 예상 시간: 10분
> 카드 디자인 선택 페이지 보완

- src/constants/cardType.ts
- src/pages/SelectCardDesignPage/SelectCardDesignPage.tsx
- #123
- 카드 선택 페이지 레이아웃 변경
- 카드 오브제와 디자인 매칭되도록 이미지 경로 수정
- 리뷰 예상시간: 1분
> 카드 선택 페이지 UI 변경

- src/components/commons/Card/VerticalCardPreview.tsx
- #136 
- 수직 카드 미리보기 컴포넌트 제작
- 스케일 0.52
- 실제 데이터 삽입
- 리뷰 예상 시간: 1분
> 수직 카드 미리보기 컴포넌트 제작

- src/features/BusinessCard/api/businessCardApi.ts
- #143 
- db 에 name 컬럼 not null > 파라미터 name 추가
- 리뷰 예상 시간: 5분
> 카드 추가 API 수정

- src/components/commons/Card/HorizontalCardPreview.tsx
- src/components/commons/QR/QRDisplayTabContent.tsx
- src/components/commons/QR/QRScannerTabContent.tsx
- #150 
- QR 모달 디자인 개선
- QR 코드 옵션 변경
- QR 스캔 탭 QR 선택 drawer 디자인
- QR 스캔 탭 QR 선택 drawer 기능
- 현재 선택된 QR이 캐러셀에 바로 표시되도록
- 돌아가기 기능 
> QR 모달 디자인 개선

- src/components/CardInfo/CareerInfo.tsx
- src/components/CardInfo/ContactInfo.tsx
- src/components/SelectCardDesignPage/types.ts
- src/components/UserPage/UserCardDrawer.tsx
- src/components/commons/Card/HorizontalCard.tsx
- src/components/commons/QR/QRScannerTabContent.tsx
- src/constants/cardType.ts
- src/features/BusinessCard/api/businessCardApi.ts
- src/features/UserPage/api/userCardListApi.ts
- src/pages/SelectCardDesignPage/SelectCardDesignPage.tsx
- src/pages/UserCardPage/UserCardPage.tsx
- src/pages/UserPage/UserPage.tsx
- src/routes/index.tsx
- #152 
> 1~2줄 사이의 요약 설명
- 내 명함 페이지 구현
> 주요 기능 및 로직에 대한 설명을 작성
- 내 명함 페이지 구현
- 그라디언트 추가
- 캐러셀 추가
- 카드 설정 drawer 추가
- 리뷰 예상 시간: 5분
> 내 명함 페이지 구현

- src/components/commons/QR/QRScanDisplayModal.tsx
- src/components/commons/QR/QRScannerTabContent.tsx
> 연관된 이슈를 모두 기재 → #[Issue번호] 형식
- #165 
> 1~2줄 사이의 요약 설명
- 모바일에서 QR 스크린 잘 보이도록 레이아웃 조정 및 스타일 변경
> 모바일에서 QR 스크린 잘 보이도록 레이아웃 조정 및 스타일 변경

- src/components/commons/QR/QRScanDisplayModal.tsx
- #167 
> 1~2줄 사이의 요약 설명
- qr 모달 레이아웃 수정
> QR 모달 레이아웃

- src/components/commons/QR/QRScanDisplayModal.tsx
- src/components/commons/QR/QRScannerTabContent.tsx
> IOS 스캔 / QR 코드 옵션 추가

- src/components/LoginPage/LoginForm.tsx
- src/constants/additionalInfoConstants.ts
- src/constants/additionalInfoSchema.ts
- src/features/User/slice/userSlice.ts
- src/hooks/Login/useAutoLogin.ts
- src/pages/AdditionalInfoPage/AdditionalInfoPage.tsx
- src/pages/CardPreviewPage/CardPreviewPage.tsx
- src/pages/SelectCardDesignPage/SelectCardDesignPage.tsx
- #184 
- 추가 정보 입력 API 연결
- 추가 정보 입력 API 연결
- 리뷰 예상 시간 - 10분
> 추가 정보 입력 API 연결

- src/App.tsx
- src/components/commons/Button/SkipButton.tsx
- src/constants/realCardScanConstants.ts
- src/hooks/Login/useAutoLogin.ts
- src/index.css
- src/pages/AdditionalInfoPage/AdditionalInfoPage.tsx
- src/pages/RealCardScanPage/RealCardScanPage.tsx
- #196 
- 실제 명함 스캔 페이지 구현
- 실제 명함 스캔 페이지 구현
- 레이아웃 조정
- 항목 정리
- 프롬프트 수정
- 명함 스캔 결과 모달 구현
- 레이아웃 조정
- 리뷰 예상 시간: 10분
> 실제 명함 스캔 페이지 구현

- src/components/UserInterestsPage/InterestSelector.tsx
- src/features/BusinessCard/api/businessCardApi.ts
- src/pages/CardPreviewPage/CardPreviewPage.tsx
- src/pages/UserInterestsPage/UserInterestsPage.tsx
- #195
- 유저 관심사 수정 API 구현
- 유저 관심사 수정 API 구현 및 연결
- 리뷰 예상 시간: 5분
> 유저 관심사 수정 API 구현
